name: Release to PyPI

on:
  release:
    types: [published]  
    
jobs:
  pypi-publish:
    name: Release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - run: pdm install
      - name: Publish package distributions to PyPI
        run: pdm publish